# Generated by Django 3.0.1 on 2020-01-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20200106_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('roll_no', models.CharField(default='0000000000', max_length=10)),
                ('total_days', models.IntegerField()),
            ],
        ),
    ]
