# Generated by Django 3.0.1 on 2020-01-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_total_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_record',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
    ]
